docker exec -i galois-db-1 sh -c 'exec mysql -u root -p"example" galois' < sql/init.sql


# create a table to receive outputs from galois, 100 and 101 represent the base currency code and the quote currency code.
create table t_clearing_result_100_101 like t_clearing_result;

# tell galois to create a new trading pair 101/100 with base_scale=4, quote_scale=4 and other parameters.
insert into t_sequence(f_cmd) values('{"base":101,"quote":100,"base_scale":4,"quote_scale":4,"taker_fee":"0.002","maker_fee":"0.002","min_amount":"0.1","min_vol":"10","enable_market_order":false,"open":true,"cmd":13}');

# account 1 tranfer 100.0 100 currency into galois
insert into t_sequence(f_cmd) values('{"currency":100,"amount":"100.0","cmd":11,"user_id":"0x0000000000000000000000000000000000000000000000000000000000000001"}');

# account 1 place an order(bid,symbol=101100,price=10.0,amount=0.5,user_id=1,order_id=1), order_id is generated by broker
insert into t_sequence(f_cmd) values('{"quote":100,"base":101,"cmd":1,"price":"10.0","amount":"0.5","order_id":1,"user_id":"0x0000000000000000000000000000000000000000000000000000000000000001"}');
