version: "3.9"
services:
  redis:
    image: "redis:alpine"
    restart: "always"
    ports:
      - "6371:6379"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: galois
      MYSQL_USER: galois
      MYSQL_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8801:8080
